using CommunityCar.Domain.Enums.AI;

namespace CommunityCar.AI.Models;

/// <summary>
/// Summary of a conversation generated by AI
/// </summary>
public class ChatSummary
{
    /// <summary>
    /// Unique identifier of the conversation
    /// </summary>
    public string ConversationId { get; set; } = string.Empty;

    /// <summary>
    /// AI-generated summary of the conversation
    /// </summary>
    public string Summary { get; set; } = string.Empty;

    /// <summary>
    /// Key topics discussed in the conversation
    /// </summary>
    public List<string> KeyTopics { get; set; } = new();

    /// <summary>
    /// Number of participants in the conversation
    /// </summary>
    public int ParticipantCount { get; set; }

    /// <summary>
    /// Total number of messages in the conversation
    /// </summary>
    public int MessageCount { get; set; }

    /// <summary>
    /// Duration of the conversation
    /// </summary>
    public TimeSpan Duration { get; set; }

    /// <summary>
    /// Overall sentiment of the conversation
    /// </summary>
    public SentimentType OverallSentiment { get; set; }

    /// <summary>
    /// Action items extracted from the conversation
    /// </summary>
    public List<string> ActionItems { get; set; } = new();
}