namespace CommunityCar.Domain.Enums.Account;

public enum ActivityType
{
    View = 1,
    Like = 2,
    Comment = 3,
    Share = 4,
    Follow = 5,
    Unfollow = 6,
    Post = 7,
    Edit = 8,
    Delete = 9,
    Search = 10,
    Login = 11,
    Logout = 12,
    Register = 13,
    ProfileUpdate = 14,
    PasswordChange = 15,
    EmailConfirmation = 16,
    TwoFactorSetup = 17,
    OAuthLink = 18,
    OAuthUnlink = 19,
    BookmarkAdd = 20,
    BookmarkRemove = 21,
    VoteUp = 22,
    VoteDown = 23,
    ReactionAdd = 24,
    ReactionRemove = 25,
    GroupJoin = 26,
    GroupLeave = 27,
    EventAttend = 28,
    EventCancel = 29,
    MessageSend = 30,
    MessageRead = 31,
    NotificationRead = 32,
    SettingsUpdate = 33,
    PrivacyUpdate = 34,
    DataExport = 35,
    DataDelete = 36,
    Other = 99
}